import { TData } from "../types"

export const months = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']

export const columns = ['Mandante', '', '', '', 'Visitante']

export const data: TData[] = [
  {
      jogo: 1,
      data: '20/nov',
      hora: '13:00',
      local: 'AL KHOR',
      grupo: 'A',
      mandante: 'Equador',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Catar'
  },
  {
      jogo: 2,
      data: '21/nov',
      hora: '13:00',
      local: 'AL THUMAMA',
      grupo: 'A',
      mandante: 'Holanda',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Senegal'
  },
  {
      jogo: 3,
      data: '25/nov',
      hora: '10:00',
      local: 'AL THUMAMA',
      grupo: 'A',
      mandante: 'Senegal',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Catar'
  },
  {
      jogo: 4,
      data: '25/nov',
      hora: '13:00',
      local: 'INTERN. KHALIFA',
      grupo: 'A',
      mandante: 'Holanda',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Equador'
  },
  {
      jogo: 5,
      data: '29/nov',
      hora: '12:00',
      local: 'AL KHOR',
      grupo: 'A',
      mandante: 'Catar',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Holanda'
  },
  {
      jogo: 6,
      data: '29/nov',
      hora: '12:00',
      local: 'INTERN. KHALIFA',
      grupo: 'A',
      mandante: 'Senegal',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Equador'
  },
  {
      jogo: 1,
      data: '21/nov',
      hora: '10:00',
      local: 'INTERN. KHALIFA',
      grupo: 'B',
      mandante: 'Irã',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Inglaterra'
  },
  {
      jogo: 2,
      data: '21/nov',
      hora: '16:00',
      local: 'AL RAYYAN',
      grupo: 'B',
      mandante: 'Gales',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Estados Unidos'
  },
  {
      jogo: 3,
      data: '25/nov',
      hora: '07:00',
      local: 'AL RAYYAN',
      grupo: 'B',
      mandante: 'Gales',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Irã'
  },
  {
      jogo: 4,
      data: '25/nov',
      hora: '16:00',
      local: 'AL KHOR',
      grupo: 'B',
      mandante: 'Estados Unidos',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Inglaterra'
  },
  {
      jogo: 5,
      data: '29/nov',
      hora: '16:00',
      local: 'AL RAYYAN',
      grupo: 'B',
      mandante: 'Inglaterra',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Gales'
  },
  {
      jogo: 6,
      data: '29/nov',
      hora: '16:00',
      local: 'AL THUMAMA',
      grupo: 'B',
      mandante: 'Estados Unidos',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Irã'
  },
  {
      jogo: 1,
      data: '22/nov',
      hora: '07:00',
      local: 'NACIONAL DE LUSAIL',
      grupo: 'C',
      mandante: 'Arábia Saldita',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Argentina'
  },
  {
      jogo: 2,
      data: '22/nov',
      hora: '13:00',
      local: 'PORTO DE DOHA',
      grupo: 'C',
      mandante: 'Polônia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'México'
  },
  {
      jogo: 3,
      data: '26/nov',
      hora: '10:00',
      local: 'CIDADE DA EDUCAÇÃO',
      grupo: 'C',
      mandante: 'Polônia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Arábia Saldita'
  },
  {
      jogo: 4,
      data: '26/nov',
      hora: '16:00',
      local: 'NACIONAL DE LUSAIL',
      grupo: 'C',
      mandante: 'México',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Argentina'
  },
  {
      jogo: 5,
      data: '30/nov',
      hora: '16:00',
      local: 'PORTO DE DOHA',
      grupo: 'C',
      mandante: 'Argentina',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Polônia'
  },
  {
      jogo: 6,
      data: '30/nov',
      hora: '16:00',
      local: 'NACIONAL DE LUSAIL',
      grupo: 'C',
      mandante: 'México',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Arábia Saldita'
  },
  {
      jogo: 1,
      data: '22/nov',
      hora: '10:00',
      local: 'CIDADE DA EDUCAÇÃO',
      grupo: 'D',
      mandante: 'Tunísia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Dinamarca'
  },
  {
      jogo: 2,
      data: '22/nov',
      hora: '16:00',
      local: 'AL WAKRAH',
      grupo: 'D',
      mandante: 'Austrália',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'França'
  },
  {
      jogo: 3,
      data: '26/nov',
      hora: '07:00',
      local: 'AL WAKRAH',
      grupo: 'D',
      mandante: 'Tunísia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Austrália'
  },
  {
      jogo: 4,
      data: '26/nov',
      hora: '13:00',
      local: 'PORTO DE DOHA',
      grupo: 'D',
      mandante: 'Dinamarca',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'França'
  },
  {
      jogo: 5,
      data: '30/nov',
      hora: '12:00',
      local: 'CIDADE DA EDUCAÇÃO',
      grupo: 'D',
      mandante: 'França',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Tunísia'
  },
  {
      jogo: 6,
      data: '30/nov',
      hora: '12:00',
      local: 'AL WAKRAH',
      grupo: 'D',
      mandante: 'Dinamarca',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Austrália'
  },
  {
      jogo: 1,
      data: '23/nov',
      hora: '10:00',
      local: 'INTERNACIONAL KHALIFA',
      grupo: 'E',
      mandante: 'Japão',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Alemanha'
  },
  {
      jogo: 2,
      data: '23/nov',
      hora: '13:00',
      local: 'AL THUMAMA',
      grupo: 'E',
      mandante: 'Costa Rica',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Espanha'
  },
  {
      jogo: 3,
      data: '27/nov',
      hora: '07:00',
      local: 'AL RAYYAN',
      grupo: 'E',
      mandante: 'Japão',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Costa Rica'
  },
  {
      jogo: 4,
      data: '27/nov',
      hora: '16:00',
      local: 'AL KHOR',
      grupo: 'E',
      mandante: 'Alemanha',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Espanha'
  },
  {
      jogo: 5,
      data: '31/nov',
      hora: '16:00',
      local: 'INTERNACIONAL KHALIFA',
      grupo: 'E',
      mandante: 'Espanha',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Japão'
  },
  {
      jogo: 6,
      data: '31/nov',
      hora: '16:00',
      local: 'AL KHOR',
      grupo: 'E',
      mandante: 'Alemanha',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Costa Rica'
  },
  {
      jogo: 1,
      data: '23/nov',
      hora: '07:00',
      local: 'AL KHOR',
      grupo: 'F',
      mandante: 'Marrocos',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Croácia'
  },
  {
      jogo: 2,
      data: '23/nov',
      hora: '16:00',
      local: 'AL RAYYAN',
      grupo: 'F',
      mandante: 'Bélgica',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Canadá'
  },
  {
      jogo: 3,
      data: '27/nov',
      hora: '10:00',
      local: 'AL THUMAMA',
      grupo: 'F',
      mandante: 'Bélgica',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Marrocos'
  },
  {
      jogo: 4,
      data: '27/nov',
      hora: '13:00',
      local: 'INTERN. KHALIFA',
      grupo: 'F',
      mandante: 'Croácia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Canadá'
  },
  {
      jogo: 5,
      data: '31/nov',
      hora: '12:00',
      local: 'AL THUMAMA',
      grupo: 'F',
      mandante: 'Canadá',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Marrocos'
  },
  {
      jogo: 6,
      data: '31/nov',
      hora: '12:00',
      local: 'AL RAYYAN',
      grupo: 'F',
      mandante: 'Croácia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Bélgica'
  },
  {
      jogo: 1,
      data: '24/nov',
      hora: '07:00',
      local: 'AL WAKRAH',
      grupo: 'G',
      mandante: 'Suíça',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Camarões'
  },
  {
      jogo: 2,
      data: '24/nov',
      hora: '16:00',
      local: 'NACIONAL DE LUSAIL',
      grupo: 'G',
      mandante: 'Brasil',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Sérvia'
  },
  {
      jogo: 3,
      data: '28/nov',
      hora: '07:00',
      local: 'AL WAKRAH',
      grupo: 'G',
      mandante: 'Sérvia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Camarões'
  },
  {
      jogo: 4,
      data: '28/nov',
      hora: '13:00',
      local: 'PORTO DE DOHA',
      grupo: 'G',
      mandante: 'Suíça',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Brasil'
  },
  {
      jogo: 5,
      data: '02/dez',
      hora: '16:00',
      local: 'NACIONAL DE LUSAIL',
      grupo: 'G',
      mandante: 'Camarões',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Brasil'
  },
  {
      jogo: 6,
      data: '02/dez',
      hora: '16:00',
      local: 'PORTO DE DOHA',
      grupo: 'G',
      mandante: 'Sérvia',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Suíça'
  },
  {
      jogo: 1,
      data: '24/nov',
      hora: '10:00',
      local: 'CIDADE DA EDUCAÇÃO',
      grupo: 'H',
      mandante: 'Coreia do Sul',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Uruguai'
  },
  {
      jogo: 2,
      data: '24/nov',
      hora: '13:00',
      local: 'PORTO DE DOHA',
      grupo: 'H',
      mandante: 'Gana',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Portugal'
  },
  {
      jogo: 3,
      data: '28/nov',
      hora: '10:00',
      local: 'CIDADE DA EDUCAÇÃO',
      grupo: 'H',
      mandante: 'Coreia do Sul',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Gana'
  },
  {
      jogo: 4,
      data: '28/nov',
      hora: '16:00',
      local: 'NACIONAL DE LUSAIL ',
      grupo: 'H',
      mandante: 'Uruguai',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Portugal'
  },
  {
      jogo: 5,
      data: '02/dez',
      hora: '12:00',
      local: 'CIDADE DA EDUCAÇÃO',
      grupo: 'H',
      mandante: 'Portugal',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Coreia do Sul'
  },
  {
      jogo: 6,
      data: '02/dez',
      hora: '12:00',
      local: 'AL WAKRAH',
      grupo: 'H',
      mandante: 'Uruguai',
      placarMandante: '',
      placarVisitante: '',
      visitante: 'Gana'
  }
]
