import { TData } from '../types'

export const months = ['jan', 'fev', 'mar', 'abr', 'mai', 'jun', 'jul', 'ago', 'set', 'out', 'nov', 'dez']

export const columns = ['Mandante', '', '', '', 'Visitante']

export const data: TData[] = [
    { 
        jogo: 1, 
        data: '20/nov', 
        hora: '13:00', 
        local: 'Al Bayt',
        grupo: 'A', 
        mandante: 'Equador',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Catar'
    },
    { 
        jogo: 2, 
        data: '21/nov', 
        hora: '13:00', 
        local: 'Al Thumama',
        grupo: 'A', 
        mandante: 'Holanda',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Senegal'
    },
    { 
        jogo: 3, 
        data: '25/nov', 
        hora: '10:00', 
        local: 'Al Thumama',
        grupo: 'A', 
        mandante: 'Senegal',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Catar'
    },
    { 
        jogo: 4, 
        data: '25/nov', 
        hora: '13:00', 
        local: 'Internacional Khalifa',
        grupo: 'A', 
        mandante: 'Holanda',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Equador'
    },
    { 
        jogo: 5, 
        data: '29/nov', 
        hora: '12:00', 
        local: 'Al Bayt',
        grupo: 'A', 
        mandante: 'Catar',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Holanda'
    },
    { 
        jogo: 6, 
        data: '29/nov', 
        hora: '12:00', 
        local: 'Internacional Khalifa',
        grupo: 'A', 
        mandante: 'Senegal',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Equador'
    },
    { 
        jogo: 1, 
        data: '21/nov', 
        hora: '10:00', 
        local: 'Internacional Khalifa',
        grupo: 'B', 
        mandante: 'Irã',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Inglaterra'
    },
    { 
        jogo: 2, 
        data: '21/nov', 
        hora: '16:00', 
        local: 'Ahmad Bin Ali',
        grupo: 'B', 
        mandante: 'Gales',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Estados Unidos'
    },
    { 
        jogo: 3, 
        data: '25/nov', 
        hora: '07:00', 
        local: 'Ahmad Bin Ali',
        grupo: 'B', 
        mandante: 'Gales',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Irã'
    },
    { 
        jogo: 4, 
        data: '25/nov', 
        hora: '16:00', 
        local: 'Al Bayt',
        grupo: 'B', 
        mandante: 'Estados Unidos',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Inglaterra'
    },
    { 
        jogo: 5, 
        data: '29/nov', 
        hora: '16:00', 
        local: 'Ahmad Bin Ali',
        grupo: 'B', 
        mandante: 'Inglaterra',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Gales'
    },
    { 
        jogo: 6, 
        data: '29/nov', 
        hora: '16:00', 
        local: 'Al Thumama',
        grupo: 'B', 
        mandante: 'Estados Unidos',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Irã'
    },
    { 
        jogo: 1, 
        data: '22/nov', 
        hora: '07:00', 
        local: 'Lusail',
        grupo: 'C', 
        mandante: 'Arábia Saldita',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Argentina'
    },
    { 
        jogo: 2, 
        data: '22/nov', 
        hora: '13:00', 
        local: 'Estádio 974',
        grupo: 'C', 
        mandante: 'Polônia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'México'
    },
    { 
        jogo: 3, 
        data: '26/nov', 
        hora: '10:00', 
        local: 'Cidade da Educação',
        grupo: 'C', 
        mandante: 'Polônia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Arábia Saldita'
    },
    { 
        jogo: 4, 
        data: '26/nov', 
        hora: '16:00', 
        local: 'Lusail',
        grupo: 'C', 
        mandante: 'México',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Argentina'
    },
    { 
        jogo: 5, 
        data: '30/nov', 
        hora: '16:00', 
        local: 'Estádio 974',
        grupo: 'C', 
        mandante: 'Argentina',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Polônia'
    },
    { 
        jogo: 6, 
        data: '30/nov', 
        hora: '16:00', 
        local: 'Lusail',
        grupo: 'C', 
        mandante: 'México',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Arábia Saldita'
    },
    { 
        jogo: 1, 
        data: '22/nov', 
        hora: '10:00', 
        local: 'Cidade da Educação',
        grupo: 'D', 
        mandante: 'Tunísia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Dinamarca'
    },
    { 
        jogo: 2, 
        data: '22/nov', 
        hora: '16:00', 
        local: 'Al Janoub',
        grupo: 'D', 
        mandante: 'Austrália',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'França'
    },
    { 
        jogo: 3, 
        data: '26/nov', 
        hora: '07:00', 
        local: 'Al Janoub',
        grupo: 'D', 
        mandante: 'Tunísia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Austrália'
    },
    { 
        jogo: 4, 
        data: '26/nov', 
        hora: '13:00', 
        local: 'Estádio 974',
        grupo: 'D', 
        mandante: 'Dinamarca',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'França'
    },
    { 
        jogo: 5, 
        data: '30/nov', 
        hora: '12:00', 
        local: 'Cidade da Educação',
        grupo: 'D', 
        mandante: 'França',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Tunísia'
    },
    { 
        jogo: 6, 
        data: '30/nov', 
        hora: '12:00', 
        local: 'Al Janoub',
        grupo: 'D', 
        mandante: 'Dinamarca',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Austrália'
    },
    { 
        jogo: 1, 
        data: '23/nov', 
        hora: '10:00', 
        local: 'Internacional Khalifa',
        grupo: 'E', 
        mandante: 'Japão',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Alemanha'
    },
    { 
        jogo: 2, 
        data: '23/nov', 
        hora: '13:00', 
        local: 'Al Thumama',
        grupo: 'E', 
        mandante: 'Costa Rica',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Espanha'
    },
    { 
        jogo: 3, 
        data: '27/nov', 
        hora: '07:00', 
        local: 'Ahmad Bin Ali',
        grupo: 'E', 
        mandante: 'Japão',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Costa Rica'
    },
    { 
        jogo: 4, 
        data: '27/nov', 
        hora: '16:00', 
        local: 'Al Bayt',
        grupo: 'E', 
        mandante: 'Alemanha',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Espanha'
    },
    { 
        jogo: 5, 
        data: '01/dez', 
        hora: '16:00', 
        local: 'Internacional Khalifa',
        grupo: 'E', 
        mandante: 'Espanha',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Japão'
    },
    { 
        jogo: 6, 
        data: '01/dez', 
        hora: '16:00', 
        local: 'Al Bayt',
        grupo: 'E', 
        mandante: 'Alemanha',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Costa Rica'
    },
    { 
        jogo: 1, 
        data: '23/nov', 
        hora: '07:00', 
        local: 'Al Bayt',
        grupo: 'F', 
        mandante: 'Marrocos',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Croácia'
    },
    { 
        jogo: 2, 
        data: '23/nov', 
        hora: '16:00', 
        local: 'Ahmad Bin Ali',
        grupo: 'F', 
        mandante: 'Bélgica',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Canadá'
    },
    { 
        jogo: 3, 
        data: '27/nov', 
        hora: '10:00', 
        local: 'Al Thumama',
        grupo: 'F', 
        mandante: 'Bélgica',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Marrocos'
    },
    { 
        jogo: 4, 
        data: '27/nov', 
        hora: '13:00', 
        local: 'Internacional Khalifa',
        grupo: 'F', 
        mandante: 'Croácia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Canadá'
    },
    { 
        jogo: 5, 
        data: '01/dez', 
        hora: '12:00', 
        local: 'Al Thumama',
        grupo: 'F', 
        mandante: 'Canadá',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Marrocos'
    },
    { 
        jogo: 6, 
        data: '01/dez', 
        hora: '12:00', 
        local: 'Ahmad Bin Ali',
        grupo: 'F', 
        mandante: 'Croácia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Bélgica'
    },
    { 
        jogo: 1, 
        data: '24/nov', 
        hora: '07:00', 
        local: 'Al Janoub',
        grupo: 'G', 
        mandante: 'Suíça',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Camarões'
    },
    { 
        jogo: 2, 
        data: '24/nov', 
        hora: '16:00', 
        local: 'Lusail',
        grupo: 'G', 
        mandante: 'Brasil',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Sérvia'
    },
    { 
        jogo: 3, 
        data: '28/nov', 
        hora: '07:00', 
        local: 'Al Janoub',
        grupo: 'G', 
        mandante: 'Sérvia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Camarões'
    },
    { 
        jogo: 4, 
        data: '28/nov', 
        hora: '13:00', 
        local: 'Estádio 974',
        grupo: 'G', 
        mandante: 'Suíça',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Brasil'
    },
    { 
        jogo: 5, 
        data: '02/dez', 
        hora: '16:00', 
        local: 'Lusail',
        grupo: 'G', 
        mandante: 'Camarões',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Brasil'
    },
    { 
        jogo: 6, 
        data: '02/dez', 
        hora: '16:00', 
        local: 'Estádio 974',
        grupo: 'G', 
        mandante: 'Sérvia',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Suíça'
    },
    { 
        jogo: 1, 
        data: '24/nov', 
        hora: '10:00', 
        local: 'Cidade da Educação',
        grupo: 'H', 
        mandante: 'Coreia do Sul',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Uruguai'
    },
    { 
        jogo: 2, 
        data: '24/nov', 
        hora: '13:00', 
        local: 'Estádio 974',
        grupo: 'H', 
        mandante: 'Gana',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Portugal'
    },
    { 
        jogo: 3, 
        data: '28/nov', 
        hora: '10:00', 
        local: 'Cidade da Educação',
        grupo: 'H', 
        mandante: 'Coreia do Sul',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Gana'
    },
    { 
        jogo: 4, 
        data: '28/nov', 
        hora: '16:00', 
        local: 'Lusail',
        grupo: 'H', 
        mandante: 'Uruguai',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Portugal'
    },
    { 
        jogo: 5, 
        data: '02/dez', 
        hora: '12:00', 
        local: 'Cidade da Educação',
        grupo: 'H', 
        mandante: 'Portugal',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Coreia do Sul'
    },
    { 
        jogo: 6, 
        data: '02/dez', 
        hora: '12:00', 
        local: 'Al Janoub',
        grupo: 'H', 
        mandante: 'Uruguai',
        placarMandante: '',
        placarVisitante: '',
        visitante: 'Gana'
    }
]
